import type {
  ActionType,
  InteractionView,
  Projection,
} from "@munchkin/contracts";

export type FigmaDesktopStateName = typeof figmaDesktopStateNames[number];

export type FigmaStateDescriptor = {
  nodeId: string;
  name: FigmaDesktopStateName;
  fixtureID: string;
  route: "/game/:id";
  component: "desktop" | "interaction" | "sheet" | "system";
  serverActions: readonly ActionType[];
  semanticCheck: string;
  visualFamily: string;
};

export const figmaDesktopStateNames = [
  "ActiveTurn",
  "HandExpanded",
  "RequiredResponse",
  "Charity",
  "Waiting",
  "Reconnecting",
  "ConnectionFailed",
  "CharacterOpen",
  "StrengthOpen",
  "OpponentOpen",
  "DoorReady",
  "PostDoorChoice",
  "RunAwayChoice",
  "RewardReceived",
  "Preparation",
  "CurseEffect",
  "HelpOffer",
  "HelpIncoming",
  "HelpAccepted",
  "RunAwayPending",
  "RunAwaySuccess",
  "RunAwayFailure",
  "RunAwayNextMonster",
  "EndTurnReady",
  "TurnPassed",
  "Death",
  "DeathLoot",
  "DeathRecovery",
  "Victory",
  "Trade",
  "Gift",
  "TheftResponse",
  "PrivateChoice",
  "StaleChoice",
  "ExpiredChoice",
  "EmptyHand",
  "InitialLoading",
  "SessionLost",
  "GameUnavailable",
  "GameFinished",
] as const;

export const figmaStateMatrix = {
  ActiveTurn: {
    nodeId: "248:5",
    name: "ActiveTurn",
    fixtureID: "full-roster-combat",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["resolve_combat"],
    semanticCheck: "desktop-active-turn",
    visualFamily: "combat-active",
  },
  HandExpanded: {
    nodeId: "253:96",
    name: "HandExpanded",
    fixtureID: "card-action-rail",
    route: "/game/:id",
    component: "sheet",
    serverActions: ["play_card"],
    semanticCheck: "hand-sheet-focus-return",
    visualFamily: "hand-expanded",
  },
  RequiredResponse: {
    nodeId: "254:221",
    name: "RequiredResponse",
    fixtureID: "interaction-material",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "required-response-actions",
    visualFamily: "interaction-response",
  },
  Charity: {
    nodeId: "256:316",
    name: "Charity",
    fixtureID: "charity-transfer",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "charity-allocation",
    visualFamily: "charity",
  },
  Waiting: {
    nodeId: "257:447",
    name: "Waiting",
    fixtureID: "stale-projection",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "waiting-actor-context",
    visualFamily: "waiting",
  },
  Reconnecting: {
    nodeId: "258:2530",
    name: "Reconnecting",
    fixtureID: "offline-stale",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "reconnect-keeps-confirmed-state",
    visualFamily: "connection-recovery",
  },
  ConnectionFailed: {
    nodeId: "258:2674",
    name: "ConnectionFailed",
    fixtureID: "offline-stale",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "connection-failure-retry",
    visualFamily: "connection-recovery",
  },
  CharacterOpen: {
    nodeId: "271:791",
    name: "CharacterOpen",
    fixtureID: "single-combat",
    route: "/game/:id",
    component: "sheet",
    serverActions: [],
    semanticCheck: "character-sheet-opener",
    visualFamily: "information-sheet",
  },
  StrengthOpen: {
    nodeId: "271:3010",
    name: "StrengthOpen",
    fixtureID: "single-combat",
    route: "/game/:id",
    component: "sheet",
    serverActions: [],
    semanticCheck: "strength-sheet-authority",
    visualFamily: "information-sheet",
  },
  OpponentOpen: {
    nodeId: "271:3216",
    name: "OpponentOpen",
    fixtureID: "full-roster-combat",
    route: "/game/:id",
    component: "sheet",
    serverActions: [],
    semanticCheck: "opponent-public-projection",
    visualFamily: "information-sheet",
  },
  DoorReady: {
    nodeId: "285:1315",
    name: "DoorReady",
    fixtureID: "single-door-choice",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["open_door"],
    semanticCheck: "door-action",
    visualFamily: "door-choice",
  },
  PostDoorChoice: {
    nodeId: "285:1388",
    name: "PostDoorChoice",
    fixtureID: "single-combat",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["resolve_combat"],
    semanticCheck: "post-door-authoritative-action",
    visualFamily: "combat-active",
  },
  RunAwayChoice: {
    nodeId: "285:1473",
    name: "RunAwayChoice",
    fixtureID: "single-run-away",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["run_away"],
    semanticCheck: "run-away-intent",
    visualFamily: "run-away",
  },
  RewardReceived: {
    nodeId: "285:1566",
    name: "RewardReceived",
    fixtureID: "run-away-result",
    route: "/game/:id",
    component: "desktop",
    serverActions: [],
    semanticCheck: "confirmed-result",
    visualFamily: "result",
  },
  Preparation: {
    nodeId: "293:1617",
    name: "Preparation",
    fixtureID: "single-preparation",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["open_door"],
    semanticCheck: "preparation-actions",
    visualFamily: "preparation",
  },
  CurseEffect: {
    nodeId: "293:1706",
    name: "CurseEffect",
    fixtureID: "target-private-choice",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "effect-choice-privacy",
    visualFamily: "interaction-choice",
  },
  HelpOffer: {
    nodeId: "293:1780",
    name: "HelpOffer",
    fixtureID: "helper-offer",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "helper-offer-descriptors",
    visualFamily: "help",
  },
  HelpIncoming: {
    nodeId: "293:1866",
    name: "HelpIncoming",
    fixtureID: "helper-invite",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "helper-invite-privacy",
    visualFamily: "help",
  },
  HelpAccepted: {
    nodeId: "293:1952",
    name: "HelpAccepted",
    fixtureID: "helper-accepted",
    route: "/game/:id",
    component: "desktop",
    serverActions: [],
    semanticCheck: "helper-confirmed-summary",
    visualFamily: "help",
  },
  RunAwayPending: {
    nodeId: "293:2026",
    name: "RunAwayPending",
    fixtureID: "run-away-response",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "run-away-pending",
    visualFamily: "run-away",
  },
  RunAwaySuccess: {
    nodeId: "294:1998",
    name: "RunAwaySuccess",
    fixtureID: "run-away-result",
    route: "/game/:id",
    component: "desktop",
    serverActions: [],
    semanticCheck: "run-away-confirmed-success",
    visualFamily: "run-away",
  },
  RunAwayFailure: {
    nodeId: "294:2072",
    name: "RunAwayFailure",
    fixtureID: "run-away-result",
    route: "/game/:id",
    component: "desktop",
    serverActions: [],
    semanticCheck: "run-away-confirmed-failure",
    visualFamily: "run-away",
  },
  RunAwayNextMonster: {
    nodeId: "294:2146",
    name: "RunAwayNextMonster",
    fixtureID: "mobile-combat-multiple",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["resolve_combat"],
    semanticCheck: "multi-monster-order",
    visualFamily: "run-away",
  },
  EndTurnReady: {
    nodeId: "294:2235",
    name: "EndTurnReady",
    fixtureID: "action-coverage",
    route: "/game/:id",
    component: "desktop",
    serverActions: ["end_turn"],
    semanticCheck: "end-turn-action",
    visualFamily: "turn-result",
  },
  TurnPassed: {
    nodeId: "294:2309",
    name: "TurnPassed",
    fixtureID: "stale-projection",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "turn-passed-waiting",
    visualFamily: "turn-result",
  },
  Death: {
    nodeId: "294:2384",
    name: "Death",
    fixtureID: "death-loot-single",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "death-public-result",
    visualFamily: "death",
  },
  DeathLoot: {
    nodeId: "295:2355",
    name: "DeathLoot",
    fixtureID: "death-loot",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "death-loot-privacy",
    visualFamily: "death",
  },
  DeathRecovery: {
    nodeId: "295:2444",
    name: "DeathRecovery",
    fixtureID: "death-loot-all-pass",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "death-recovery-result",
    visualFamily: "death",
  },
  Victory: {
    nodeId: "295:2518",
    name: "Victory",
    fixtureID: "victory-six-player",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "victory-terminal-surface",
    visualFamily: "victory",
  },
  Trade: {
    nodeId: "295:2592",
    name: "Trade",
    fixtureID: "economy-offer",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "trade-offer-privacy",
    visualFamily: "economy",
  },
  Gift: {
    nodeId: "295:2678",
    name: "Gift",
    fixtureID: "economy-actions",
    route: "/game/:id",
    component: "interaction",
    serverActions: ["propose_gift"],
    semanticCheck: "gift-action-descriptor",
    visualFamily: "economy",
  },
  TheftResponse: {
    nodeId: "295:2764",
    name: "TheftResponse",
    fixtureID: "theft-response",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "theft-counter-privacy",
    visualFamily: "economy",
  },
  PrivateChoice: {
    nodeId: "296:2748",
    name: "PrivateChoice",
    fixtureID: "target-private-choice",
    route: "/game/:id",
    component: "interaction",
    serverActions: [],
    semanticCheck: "private-choice-no-leak",
    visualFamily: "interaction-choice",
  },
  StaleChoice: {
    nodeId: "296:2837",
    name: "StaleChoice",
    fixtureID: "stale-projection",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "stale-choice-recovery",
    visualFamily: "connection-recovery",
  },
  ExpiredChoice: {
    nodeId: "296:2911",
    name: "ExpiredChoice",
    fixtureID: "expired-choice",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "expired-choice-confirmed",
    visualFamily: "interaction-choice",
  },
  EmptyHand: {
    nodeId: "296:2985",
    name: "EmptyHand",
    fixtureID: "empty-hand",
    route: "/game/:id",
    component: "sheet",
    serverActions: ["open_door"],
    semanticCheck: "empty-hand-fallback",
    visualFamily: "empty",
  },
  InitialLoading: {
    nodeId: "296:3058",
    name: "InitialLoading",
    fixtureID: "single-combat",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "initial-loading-skeleton",
    visualFamily: "system",
  },
  SessionLost: {
    nodeId: "296:3133",
    name: "SessionLost",
    fixtureID: "offline-stale",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "session-lost-no-projection",
    visualFamily: "system",
  },
  GameUnavailable: {
    nodeId: "297:3103",
    name: "GameUnavailable",
    fixtureID: "offline-stale",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "game-unavailable-recovery",
    visualFamily: "system",
  },
  GameFinished: {
    nodeId: "297:3177",
    name: "GameFinished",
    fixtureID: "single-finished",
    route: "/game/:id",
    component: "system",
    serverActions: [],
    semanticCheck: "finished-terminal-surface",
    visualFamily: "victory",
  },
} satisfies Record<FigmaDesktopStateName, FigmaStateDescriptor>;

export const figmaStateDescriptors = figmaDesktopStateNames.map(
  (name) => figmaStateMatrix[name],
);

export type ActionCoverage = {
  fixtureID: string;
  semanticCheck: string;
};

export const actionCoverage = {
  start: {fixtureID: "action-coverage", semanticCheck: "action-start"},
  finish_setup: {fixtureID: "action-coverage", semanticCheck: "action-finish-setup"},
  play_card: {fixtureID: "action-coverage", semanticCheck: "action-play-card"},
  play_target_effect: {fixtureID: "action-coverage", semanticCheck: "action-play-target-effect"},
  equip_item: {fixtureID: "action-coverage", semanticCheck: "action-equip-item"},
  unequip_item: {fixtureID: "action-coverage", semanticCheck: "action-unequip-item"},
  discard_card: {fixtureID: "action-coverage", semanticCheck: "action-discard-card"},
  sell_items: {fixtureID: "action-coverage", semanticCheck: "action-sell-items"},
  open_door: {fixtureID: "action-coverage", semanticCheck: "action-open-door"},
  look_for_trouble: {fixtureID: "action-coverage", semanticCheck: "action-look-for-trouble"},
  loot_room: {fixtureID: "action-coverage", semanticCheck: "action-loot-room"},
  use_ability: {fixtureID: "action-coverage", semanticCheck: "action-use-ability"},
  resolve_combat: {fixtureID: "action-coverage", semanticCheck: "action-resolve-combat"},
  run_away: {fixtureID: "action-coverage", semanticCheck: "action-run-away"},
  choose_effect: {fixtureID: "action-coverage", semanticCheck: "action-choose-effect"},
  resolve_charity: {fixtureID: "action-coverage", semanticCheck: "action-resolve-charity"},
  propose_trade: {fixtureID: "action-coverage", semanticCheck: "action-propose-trade"},
  propose_gift: {fixtureID: "action-coverage", semanticCheck: "action-propose-gift"},
  attempt_theft: {fixtureID: "action-coverage", semanticCheck: "action-attempt-theft"},
  end_turn: {fixtureID: "action-coverage", semanticCheck: "action-end-turn"},
  fight: {fixtureID: "action-coverage", semanticCheck: "action-fight"},
  loot: {fixtureID: "action-coverage", semanticCheck: "action-loot"},
} satisfies Record<ActionType, ActionCoverage>;

type InteractionKind = InteractionView["public_kind"];

export const interactionCoverage = {
  response_window: "interaction-pass-only",
  combat_response: "interaction-material",
  combat_help_offer: "helper-invite",
  target_response: "target-response",
  run_away_response: "run-away-response",
  private_choice: "target-private-choice",
  economy_offer: "economy-offer",
  charity_transfer: "charity-transfer",
  theft_response: "theft-response",
  death_loot_priority: "death-loot",
} satisfies Record<InteractionKind, string>;

type Phase = Exclude<Projection["turn"]["phase"], "">;

export const phaseCoverage = {
  setup: "single-setup",
  preparation: "single-preparation",
  door_choice: "single-door-choice",
  combat: "single-combat",
  run_away: "single-run-away",
  resolve_effect: "target-private-choice",
  charity: "single-charity",
  end_turn: "single-finished",
} satisfies Record<Phase, string>;

export const statusCoverage = {
  lobby: "lobby-state",
  active: "single-combat",
  finished: "single-finished",
} satisfies Record<Projection["status"], string>;

export const figmaFlowModes = {
  Cards3: {
    nodeId: "291:1587",
    fixtureID: "mobile-combat-multiple",
    semanticCheck: "flow-cards-three",
  },
  Cards2Summary: {
    nodeId: "291:3622",
    fixtureID: "single-combat",
    semanticCheck: "flow-cards-summary",
  },
  Result: {
    nodeId: "291:3655",
    fixtureID: "run-away-result",
    semanticCheck: "flow-result",
  },
  System: {
    nodeId: "291:3690",
    fixtureID: "offline-stale",
    semanticCheck: "flow-system",
  },
  Empty: {
    nodeId: "292:1617",
    fixtureID: "empty-hand",
    semanticCheck: "flow-empty",
  },
} as const;

export const figmaCompactHandoffs = {
  integratedStates: {
    nodeId: "147:671",
    route: "/game/:id",
    viewport: "360x640",
    component: "mobile-game-table",
    source: "Integrated States / Compact Integrated States / Board · 360×640",
    fixtureIDs: ["single-combat", "mobile-combat-multiple", "offline-stale"],
  },
  coreLoop: {
    nodeId: "160:1140",
    route: "/game/:id",
    viewport: "360x640",
    component: "mobile-game-table",
    source: "Core Loop & Interactions / Board · 360×640",
    fixtureIDs: ["single-setup", "single-door-choice", "single-run-away", "run-away-result"],
  },
  lobbySelectedB: {
    nodeId: "225:14",
    route: "/",
    viewport: "360x640",
    component: "lobby-entry",
    source: "Lobby Entry / Selected B Flow · 360×640",
    fixtureIDs: ["lobby-state"],
  },
  lobbyDesktopSelectedB: {
    nodeId: "240:50",
    route: "/",
    viewport: "1440x900",
    component: "lobby-entry",
    source: "Lobby Entry / Desktop States · 1440×900",
    fixtureIDs: ["lobby-state"],
  },
} as const;

export const excludedFigmaSources = [
  {
    nodeId: "122:3",
    viewport: "360x800",
    reason: "User explicitly excluded 360×800 screenshots; compact parity uses only 360×640 source nodes.",
  },
] as const;

export const unresolvedFigmaHandoffs = [] as const;
