global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false
  insecure: false

ping:
  entryPoint: web

entryPoints:
  web:
    address: ":8080"
    transport:
      respondingTimeouts:
        readTimeout: 60s
        writeTimeout: 60s
        idleTimeout: 120s
  websecure:
    address: ":8443"
    transport:
      respondingTimeouts:
        readTimeout: 60s
        writeTimeout: 60s
        idleTimeout: 120s

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  le:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  format: json
  level: INFO

accessLog:
  format: json
  bufferingSize: 100
  fields:
    headers:
      defaultMode: drop

metrics:
  prometheus: {}
